function output = my_interface_correction
    bg = uibuttongroup('Visible','off',...
                  'Position',[0.9 0 .1 1]);             
    % Create three radio buttons in the button group.
    uicontrol(bg,'Style','radiobutton',...
              'String','No Correction',...
              'Position',[7 400 150 30],...
              'HandleVisibility','off');
    uicontrol(bg,'Style','text',...
              'String','----Correction----',...
              'Position',[7 350 100 30],...
              'HandleVisibility','off');

    uicontrol(bg,'Style',...
                      'radiobutton',...
                      'String','Remove',...
                      'Position',[7 320 150 30],...
                      'HandleVisibility','off');   
    uicontrol(bg,'Style','radiobutton',...
                  'String','Fill',...
                  'Position',[7 290 150 30],...
                  'HandleVisibility','off');
    bg.Visible = 'on';
    pause;   

    output = get(bg.SelectedObject,'String');
    
    if strcmp(output,'Remove')
         uicontrol(gcf,'Style','text',...
              'String','*지울 영역을 선택!',...
              'Position',[1160 150 120 50],...
              'HandleVisibility','off');
    elseif strcmp(output,'Fill')
         uicontrol(gcf,'Style','text',...
              'String','*채울 영역을 선택!',...
              'Position',[1160 150 120 50],...
              'HandleVisibility','off');
      elseif strcmp(output,'No Correction')
        uicontrol(gcf,'Style','text',...
              'String','*OK!',...
              'Position',[1160 150 120 50],...
              'HandleVisibility','off');
    end
end